version: "3.8"
services:
  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./jupyter.env
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./src:/workspace/src
      - ./data:/workspace/data
      - ./reports:/workspace/reports
    user: root
    ports:
      - 8888:8888
      - 4040:4040
    networks:
      - jupyter-starter
networks:
  jupyter-starter:
    name: jupyter-starter
    driver: bridge
